# Generated by Django 2.0 on 2017-12-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20171228_1813'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='tweet',
            name='updated',
        ),
    ]
