# Generated by Django 2.0 on 2018-01-01 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_tweet_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweet',
            options={'ordering': ['-timestamp']},
        ),
    ]
